# Generated by Django 4.2.14 on 2024-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='uploads/images/profile.jpg', upload_to='uploads/images')),
                ('product', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('quantity', models.CharField(default='0', max_length=150)),
            ],
        ),
    ]
