# Generated by Django 4.2.14 on 2024-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='uploads/images/profile.jpg', upload_to='uploads/sliders')),
                ('about_slide', models.CharField(max_length=150)),
            ],
        ),
    ]
