# Generated by Django 4.2.14 on 2024-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sliders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('androidicon', models.ImageField(default='uploads/images/profile.jpg', upload_to='uploads/configs')),
                ('roundicon', models.ImageField(default='uploads/images/profile.jpg', upload_to='uploads/configs')),
                ('androidlabel', models.CharField(max_length=150)),
            ],
        ),
    ]
